---

- name: Install Netdata
  shell: >
    bash <(curl -Ss https://my-netdata.io/kickstart.sh)
    --stable-channel
    --dont-wait
  args:
    executable: "/bin/bash"
    creates: "/usr/sbin/netdata"
