---

- name: Install Netdata
  shell: >
    bash <(curl -Ss https://my-netdata.io/kickstart.sh)
    --stable-channel
    --dont-wait
  args:
    executable: "/bin/bash"
    creates: "/usr/sbin/netdata"

- name: Disable health alarm alerts
  ini_file:
    path: "{{ netdata_config_path }}"
    section: "health"
    option: "enabled"
    value: "no"
    state: present
  notify:
    - reload netdata
  when: netdata_disable_alerts
